CDPD-91363: Fix Junit test discovery failure - NoSuchMethodError
In hms-catalog/pom.xml
- modify maven-surefire-plugin version to use hive project's version instead of apache POM
- align junit-jupiter version to be the same across project
- add junit vintage dependency to execute tests

Change-Id: Ieea0ce5118d566433c26a9b3971e9e6ed2d21cab