CDPD-31883 HIVE-25675: Intermittent PSQLException when trying to connect to Postgres in tests (Stamatis Zampetakis, reviewed by Peter Vary)
Sometimes when we try to connect to Postgres, the database is not yet
completely ready despite the fact that the respective port is open thus
leading to the following exception.

PSQLException: FATAL: the database system is starting up

1. Ensure the database is ready by checking a certain message appears
two times in the logs.
2. Remove the now unused logger.

Closes #2767

(cherry-picked from commit a72db99676ca6a79b414906ab78963a3e955ae69)

Complete commit 6aaa9b739d82007618e5103d5d23084e6d8bd4e9 by adding
missing changes in Postgres.java

Change-Id: I6ef816082df9a8592bcf0f61fd2c41e0d72dec2e