CDPD-58200: NoClassDefFoundError: org/xerial/snappy/Snappy when running iceberg tests
When transitive dependency to snappy-java is removed (for whatever
reason) iceberg tests fail with NoClassDefFoundError since Iceberg uses
SNAPPY compression by default to write data files.

To prevent such failures given the imminent removal of kafka-client
(transitively bringing snappy-java) we must add an explicit dependency
to the snappy compression library in iceberg-handler.

Change-Id: I957c08f9b30980ef2f67da82a03471546dbb3395