CDPD-68219: Upgrade CDWH stack to Calcite 1.33.0 BUILD_CUSTOM_CALCITE:zabetak:cdw-master-133 SKIP_POM_PATCH (#1428)
* CDPD-68219: HIVE-27102: Upgrade Calcite version from 1.25.0 to 1.33.0

1. Upgrade Calcite version from 1.25.0 to 1.33.0 and update code to address breaking changes and avoid compilation failures:
* Add HiveJdbcImplementor#visit(JdbcTableScan) to address breaking change from CALCITE-4640.
* Add HiveRuleConfig to address the removal of RelRule.Config.EMPTY by CALCITE-4839. This allows to instantiate RelRule subclasses without relying on the immutables annotation processor.
* Adapt RelNode constructors and pass empty hints to address breaking change from in CALCITE-4640.
* Simplify HiveDruidRules by using the config from respective rules in Calcite.
* Adapt HiveRelFactories due to changes in ProjectFactory API (CALCITE-4199, CALCITE-5127).
2. Upgrade Avatica version from 1.12.0 to 1.23.0 (required by Calcite).
3. Add explicit dependency to org.immutables:value-annotations to avoid compilation failures due to missing Value annotation.
Since we don't want to propagate the dependency to dependent projects we declared it at provided scope. The problem appears cause annotation pre-processing is enabled.
4. Add explicit dependency to org.locationtech.jts:jts-core and declare it at runtime scope.
The jts-core is a transitive dependency used by calcite-core. In order for CBO to function properly the jar must be present in the classpath. If the jar is missing, Hiveserver2 will fail during startup with ClassNotFoundException.
Normally we wouldn't need to explicitly declare transitive dependencies, but we are forced to do so cause calcite is partially shaded in hive-exec module. We are already doing the same for various other calcite deps such as janino, avatica, etc.
5. Register HiveIn as SqlKind.OTHER_FUNCTION and distinguish it from SqlKind.IN which is now reserved for usage inside RexSubQuery
6. Replace checks for SqlKind.IN in RexCall, which can no longer appear, with checks on HiveIn operator directly.
7. Implement new rules and converters to transform/expand the internal SEARCH operator to traditional conjunctions/disjunctions of standard comparisons operators, IN, and BETWEEN.
8. Copy and use Lopt classes from Calcite with the fix for (CALCITE-6737) to avoid changes in join order when queries contain self-joins.
9. Move rollup aggregation logic from HiveRelBuilder to the appropriate SqlAggFunction subclass and remove redundant overrides in HiveMaterializedViewRule.
CALCITE-4342 made rollup strategy a first class citizen of the SqlAggFunction interface so each function can return its own rollup if available.
It's no longer necessary to pass from the RelBuilder and basically whenever we need to obtain a rollup we have to ask directly the SqlAggFunction.
As part of CALCITE-4342, the MaterializedViewRule#getRollup method was deprecated so this refactoring is necessary for the Hive MV rules to function properly.
10. Make HivePreFilteringRule a reduction rule to address fixpoint bug (StackOverflowError) triggered by changes in RelMetadataQuery#getPulledUpPredicates (CALCITE-5036).
11. Add HiveTypeFactory to avoid redundant nullability CAST to ARRAY that in some cases (lateral_view_outer.q) leads to wrong results. The redundant CAST is a side-effect from fixing CALCITE-4603.
12. Handle ROW type literals in RexNodeConverter#transformInToOrOperands
After the upgrade a ROW RexCall with constants is reduced/folded to a RexLiteral of ROW types so we must adapt the IN transformation logic otherwise the ROW specific code will not kick in.
Although this is merely an optimization it has impact on correctness (due to existing Hive bugs) so it's necessary to keep it working.
13. Enhance FilterSelectivityEstimator to provide better estimates for NOT
14. Use RelBuilder instead of RexBuilder in TestHivePushdownSnapshotFilterRule.
Code is more readable and avoids creating invalid expressions with wrong types as it was the case before.
15. Disable RelBuilder simplifications in TestHivePointLookupOptimizerRule to avoid the introduction of SEARCH in the input plans. The rule is meant to handle disjunctions (OR) so we want to keep the input plans intact in order to properly test the rule. If the input plan is simplified to SEARCH or something else then test coverage will change that is not desired.

The plan and behavior changes that occur as part of the upgrade can be summarized into the following categories. An additional (R*) classifier, is used to denote subtle regressions that will be fixed by follow-up patches. Each change is associated with some represantive .q.out files that illustrate the overall impact on query plans.

Category I: Changes that are mostly cosmetic and do not affect the performance or behavior of the queries.

1. Changes in the output of EXPLAIN EXTENDED (OPTIMIZED SQL)
* Less parentheses [auto_join_reordering_values.q.out]
* Less spaces when formatting IN, ARRAY, etc. [alter_partition_coltype.q.out, autoColumnStats_5a.q.out]
* VALUES clause with one entry becomes SELECT with literals [acid_nullscan.q.out]
* New OPTIMIZED SQL entries since various bugs in RelToSqlConverter were fixed [pcs.q.out]
* Explicit CROSS JOIN clause instead of comma separated sub-queries [tez_fixed_bucket_pruning.q.out]
2. Different formatting (toString) for DOUBLE literals [rule_exclusion_config.q.out]
3. Extra "fields" attributes in the output of EXPLAIN FORMATTED (R*) [concat_op.q.out]
4. IN clause literals sorted alphabetically [dynamic_partition_pruning_2.q.out]
5. Different aliases for expressions inside projects (e.g., lots of EXPR$ in CBO plans) [cardinality_preserving_join_opt.q.out]
6. Result changes due to missing ORDER BY in queries [partition_wise_fileformat2.q.out]

Category II: Changes that can slightly affect the performance of queries increasing/decreasing CPU cycles.

1. Predicate order changes in filters [auto_join5.q.out]
2. Redundant IS NOT NULL predicates (R*) [explainuser_4.q.out, pointlookup5.q.out]
3. Redundant CAST around COALESCE (R*) [cbo_aggregate_reduce_functions_rule.q.out]
3. Pull-up constants from nullsafe predicates [is_distinct_from.q.out, join_nullsafe.q.out, orc_predicate_pushdown.q.out]
4. Residual filter predicates in joins (R*) [ppd_join.q.out]

Category III: Changes that can lead to significant changes in query performance.

1. Expression simplifications in project/filter/join
* IN, BETWEEN, and comparison operators (<,>,>=,<=,==,<>) are simplified together by exploiting the SEARCH operator [bucketsortoptimize_insert_7.q.out]
* x NOT BETWEEN 10 AND 20 is transformed to x < 10 OR x > 20 [udf_between.q.out]
* x <> 10 is transformed to x > 10 OR x < 10 (R*) [ppd_join3.q.out]
* Simplifications with arithmetic operators [materialized_view_rewrite_8.q.out, tez_vector_dynpart_hashjoin_2.q.out]
2. Disjunctive predicate pushdown for joins (R*) [cbo_join_transitive_pred_loop_1.q.out, correlationoptimizer8.q.out]
3. LEFT OUTER to INNER joins due to CALCITE-5247 [subquery_ANY.q.out]
4. Better orders for LEFT/RIGHT/ANTI joins due to CALCITE-4208 [auto_join30.q.out, subquery_join_rewrite.q.out]
5. Unconditional OR to IN tranformations [in_typecheck_char.q.out, pointlookup2.q.out]
6. Extra partition pruning due to simplifications [select_unquote_or.q.out]

Co-authored-by: Stamatis Zampetakis <zabetak@gmail.com>
Co-authored-by: Krisztian Kasa <kasakrisz2@gmail.com>
Change-Id: Ideb4352699fc55343bc4b50c1d46c2c2bb000f3e

* CDPD-84190: HIVE-28958: Tez job failed with: NoClassDefFoundError: org/locationtech/jts/geom/Geometry

Change-Id: Ib20e7a748cdafb2de36c06f4d8311b2343b22bd0

---------

Co-authored-by: Soumyakanti Das <soumyakanti.das.08@gmail.com>
Co-authored-by: Stamatis Zampetakis <zabetak@gmail.com>
Co-authored-by: Krisztian Kasa <kasakrisz2@gmail.com>
Co-authored-by: Butao Zhang <zhangbutao@cmss.chinamobile.com>