CDPD-31883 HIVE-25832: Exclude Category-X JDBC drivers from binary distribution (Stamatis Zampetakis, reviewed by Alessandro Solimando, Zoltan Haindrich)
Exclude drivers for Oracle, MySQL, and MariaDB to avoid licensing
violations.

Misc:
1. Group all JDBC drivers in metastore-server pom.xml together for
readability.
2. Add MariaDB driver in metastore-server pom.xml for keeping things
uniform.

Closes #2905

(cherry-picked from commit 588e634308afbeb02b85e094b3d63529dacb7f6f)

1. Leave out the changes in metastore-server pom.xml since the module
does not exist.
2. Remove JDBC driver excludes from packaging/src/main/assembly/bin.xml
since dependencies (e.g., beeline) are different from upstream and the
respective drivers are not added in the packaged distribution anyways.
Keeping these changes would make the build fail with the following
error: Assembly is not configured correctly: One or more filters had unmatched criteria.

Change-Id: I78e161a47c016f0275517ab3c633d0c198ab0194